// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: chord.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeyServiceClient is the client API for KeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyServiceClient interface {
	RPCLookup(ctx context.Context, in *Key, opts ...grpc.CallOption) (*NodeIp, error)
	RPCRegisterNode(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*NodeIp, error)
	RPCGetSuccessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeIp, error)
	RPCClosestPrecedingFinger(ctx context.Context, in *IdM, opts ...grpc.CallOption) (*NodeIp, error)
	RPCFindSuccessor(ctx context.Context, in *Id, opts ...grpc.CallOption) (*NodeIp, error)
	RPCGetPredecessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeIp, error)
	RPCNotify(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*Empty, error)
	RPCDepart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	RPCNotifySucc(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*Empty, error)
	RPCNotifyPred(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*Empty, error)
	RPCRemoveNode(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*Empty, error)
	RPCAddkey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error)
	RPCGetKeys(ctx context.Context, in *Key, opts ...grpc.CallOption) (*KeyMap, error)
	RPCTransferKeys(ctx context.Context, in *KeyMap, opts ...grpc.CallOption) (*Empty, error)
}

type keyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyServiceClient(cc grpc.ClientConnInterface) KeyServiceClient {
	return &keyServiceClient{cc}
}

func (c *keyServiceClient) RPCLookup(ctx context.Context, in *Key, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCLookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCRegisterNode(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCRegisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCGetSuccessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCGetSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCClosestPrecedingFinger(ctx context.Context, in *IdM, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCClosestPrecedingFinger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCFindSuccessor(ctx context.Context, in *Id, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCFindSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCGetPredecessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCGetPredecessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCNotify(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCDepart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCDepart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCNotifySucc(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCNotifySucc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCNotifyPred(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCNotifyPred", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCRemoveNode(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCRemoveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCAddkey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCAddkey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCGetKeys(ctx context.Context, in *Key, opts ...grpc.CallOption) (*KeyMap, error) {
	out := new(KeyMap)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCGetKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCTransferKeys(ctx context.Context, in *KeyMap, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCTransferKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyServiceServer is the server API for KeyService service.
// All implementations must embed UnimplementedKeyServiceServer
// for forward compatibility
type KeyServiceServer interface {
	RPCLookup(context.Context, *Key) (*NodeIp, error)
	RPCRegisterNode(context.Context, *NodeIp) (*NodeIp, error)
	RPCGetSuccessor(context.Context, *Empty) (*NodeIp, error)
	RPCClosestPrecedingFinger(context.Context, *IdM) (*NodeIp, error)
	RPCFindSuccessor(context.Context, *Id) (*NodeIp, error)
	RPCGetPredecessor(context.Context, *Empty) (*NodeIp, error)
	RPCNotify(context.Context, *NodeIp) (*Empty, error)
	RPCDepart(context.Context, *Empty) (*Empty, error)
	RPCNotifySucc(context.Context, *NodeIp) (*Empty, error)
	RPCNotifyPred(context.Context, *NodeIp) (*Empty, error)
	RPCRemoveNode(context.Context, *NodeIp) (*Empty, error)
	RPCAddkey(context.Context, *Key) (*Empty, error)
	RPCGetKeys(context.Context, *Key) (*KeyMap, error)
	RPCTransferKeys(context.Context, *KeyMap) (*Empty, error)
	mustEmbedUnimplementedKeyServiceServer()
}

// UnimplementedKeyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeyServiceServer struct {
}

func (UnimplementedKeyServiceServer) RPCLookup(context.Context, *Key) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCLookup not implemented")
}
func (UnimplementedKeyServiceServer) RPCRegisterNode(context.Context, *NodeIp) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCRegisterNode not implemented")
}
func (UnimplementedKeyServiceServer) RPCGetSuccessor(context.Context, *Empty) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCGetSuccessor not implemented")
}
func (UnimplementedKeyServiceServer) RPCClosestPrecedingFinger(context.Context, *IdM) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCClosestPrecedingFinger not implemented")
}
func (UnimplementedKeyServiceServer) RPCFindSuccessor(context.Context, *Id) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCFindSuccessor not implemented")
}
func (UnimplementedKeyServiceServer) RPCGetPredecessor(context.Context, *Empty) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCGetPredecessor not implemented")
}
func (UnimplementedKeyServiceServer) RPCNotify(context.Context, *NodeIp) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCNotify not implemented")
}
func (UnimplementedKeyServiceServer) RPCDepart(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCDepart not implemented")
}
func (UnimplementedKeyServiceServer) RPCNotifySucc(context.Context, *NodeIp) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCNotifySucc not implemented")
}
func (UnimplementedKeyServiceServer) RPCNotifyPred(context.Context, *NodeIp) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCNotifyPred not implemented")
}
func (UnimplementedKeyServiceServer) RPCRemoveNode(context.Context, *NodeIp) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCRemoveNode not implemented")
}
func (UnimplementedKeyServiceServer) RPCAddkey(context.Context, *Key) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCAddkey not implemented")
}
func (UnimplementedKeyServiceServer) RPCGetKeys(context.Context, *Key) (*KeyMap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCGetKeys not implemented")
}
func (UnimplementedKeyServiceServer) RPCTransferKeys(context.Context, *KeyMap) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCTransferKeys not implemented")
}
func (UnimplementedKeyServiceServer) mustEmbedUnimplementedKeyServiceServer() {}

// UnsafeKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyServiceServer will
// result in compilation errors.
type UnsafeKeyServiceServer interface {
	mustEmbedUnimplementedKeyServiceServer()
}

func RegisterKeyServiceServer(s grpc.ServiceRegistrar, srv KeyServiceServer) {
	s.RegisterService(&KeyService_ServiceDesc, srv)
}

func _KeyService_RPCLookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCLookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCLookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCLookup(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCRegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCRegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCRegisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCRegisterNode(ctx, req.(*NodeIp))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCGetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCGetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCGetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCGetSuccessor(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCClosestPrecedingFinger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdM)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCClosestPrecedingFinger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCClosestPrecedingFinger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCClosestPrecedingFinger(ctx, req.(*IdM))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCFindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCFindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCFindSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCFindSuccessor(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCGetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCGetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCGetPredecessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCGetPredecessor(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCNotify(ctx, req.(*NodeIp))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCDepart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCDepart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCDepart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCDepart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCNotifySucc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCNotifySucc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCNotifySucc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCNotifySucc(ctx, req.(*NodeIp))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCNotifyPred_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCNotifyPred(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCNotifyPred",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCNotifyPred(ctx, req.(*NodeIp))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCRemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCRemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCRemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCRemoveNode(ctx, req.(*NodeIp))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCAddkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCAddkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCAddkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCAddkey(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCGetKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCGetKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCGetKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCGetKeys(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCTransferKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCTransferKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCTransferKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCTransferKeys(ctx, req.(*KeyMap))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyService_ServiceDesc is the grpc.ServiceDesc for KeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chord.KeyService",
	HandlerType: (*KeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RPCLookup",
			Handler:    _KeyService_RPCLookup_Handler,
		},
		{
			MethodName: "RPCRegisterNode",
			Handler:    _KeyService_RPCRegisterNode_Handler,
		},
		{
			MethodName: "RPCGetSuccessor",
			Handler:    _KeyService_RPCGetSuccessor_Handler,
		},
		{
			MethodName: "RPCClosestPrecedingFinger",
			Handler:    _KeyService_RPCClosestPrecedingFinger_Handler,
		},
		{
			MethodName: "RPCFindSuccessor",
			Handler:    _KeyService_RPCFindSuccessor_Handler,
		},
		{
			MethodName: "RPCGetPredecessor",
			Handler:    _KeyService_RPCGetPredecessor_Handler,
		},
		{
			MethodName: "RPCNotify",
			Handler:    _KeyService_RPCNotify_Handler,
		},
		{
			MethodName: "RPCDepart",
			Handler:    _KeyService_RPCDepart_Handler,
		},
		{
			MethodName: "RPCNotifySucc",
			Handler:    _KeyService_RPCNotifySucc_Handler,
		},
		{
			MethodName: "RPCNotifyPred",
			Handler:    _KeyService_RPCNotifyPred_Handler,
		},
		{
			MethodName: "RPCRemoveNode",
			Handler:    _KeyService_RPCRemoveNode_Handler,
		},
		{
			MethodName: "RPCAddkey",
			Handler:    _KeyService_RPCAddkey_Handler,
		},
		{
			MethodName: "RPCGetKeys",
			Handler:    _KeyService_RPCGetKeys_Handler,
		},
		{
			MethodName: "RPCTransferKeys",
			Handler:    _KeyService_RPCTransferKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chord.proto",
}
